// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcxdjwfkvzweiuyoxuyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjeGRqd2Zrdnp3ZWl1eW94dXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4MTc3MzksImV4cCI6MjA1MjM5MzczOX0.S_8pLnoBpxp1950WXPXMVHxyxMYyjIxSqUMlHbuzQCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);